apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kiali-server
  namespace: istio-system
spec:
  releaseName: kiali-server
  chart:
    spec:
      chart: kiali-server
      sourceRef:
        kind: HelmRepository
        name: kiali-server
        namespace: istio-system
  interval: 15m
  # Default values
  values:
    server:
      web_fqdn: example.com
